AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Money Club Lamda.

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.moneyclub.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/club-0.0.1-SNAPSHOT.jar
      MemorySize: 2048
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 900
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MarketingDBApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: mcMarketingDb